= Create vector index

Vector indexes allow Neo4j to run similarity queries across the whole database.
The example below shows how to create a vector index for movie embeddings, under the name of `moviePlots`.

[TIP]
Provide a dimension when xref:setup/vector-index.adoc[creating a vector index] as shown in the examples below, as it ensures that only vectors of that size are indexed and makes dimension mismatches fail explicitly at query time.

[.tabbed-example]
====
[.include-with-SentenceTransformers]
=====
[source, cypher]
----
CREATE VECTOR INDEX moviePlots
FOR (m:Movie)
ON m.embedding
OPTIONS {indexConfig: {
    `vector.dimensions`: 384,  // <1>
    `vector.similarity_function`: 'cosine'  // <2>
}}
----

<1> For embeddings generated with the SentenceTransformers model `all-MiniLM-L6-v2`.
If you use a different model, update this value to match its embedding dimension.
<2> The cosine similarity function is the most common choice. For more details and other options, see link:https://neo4j.com/docs/cypher-manual/current/indexes/semantic-indexes/vector-indexes/#similarity-functions[Vector indexes -> Cosine and Euclidean similarity functions].

=====

[.include-with-OpenAI]
=====

////
[source, cypher, test-setup]
----
DROP INDEX moviePlots
----
////

[source, cypher]
----
CREATE VECTOR INDEX moviePlots
FOR (m:Movie)
ON m.embedding
OPTIONS {indexConfig: {
    `vector.dimensions`: 1536,  // <1>
    `vector.similarity_function`: 'cosine'  // <2>
}}
----

<1> For embeddings generated with the OpenAI model `text-embedding-3-small`.
If you use a different model, update this value to match its embedding dimension.
<2> The cosine similarity function is the most common choice. For more details and other options, see link:https://neo4j.com/docs/cypher-manual/current/indexes/semantic-indexes/vector-indexes/#similarity-functions[Vector indexes -> Cosine and Euclidean similarity functions].

=====

====

For more information on vector indexes, see link:https://neo4j.com/docs/cypher-manual/current/indexes/semantic-indexes/vector-indexes/[Cypher -> Indexes -> Vector indexes].
